### ISSUE TITLE
Plans to allow awscli configuration?

### ISSUE THREAD

**Issue by jcderose** [awslabs/awscli-cookbook#10]
Several non-supermarket cookbooks allow me to install the AWS CLI AND configure the CLI in a single recipe. Do you have any plans to implement this functionality, too? I'd much rather use the AWS-managed cookbook for CLI configuration than an unknown third-party source.

**Comment by hyandell** [comment]
Hi Jesse,

Nick, the author of this repository, is now supporting the code over at his https://github.com/nickryand/cloudcli-cookbook fork. I encourage you to follow up with him there if this is still desired/unimplemented. I'm going to close the issue on the awscli-cookbook side as I'm updating the repo to point in general to Nick's fork.
