### ISSUE TITLE
No longer works under chef 11.10.4

### ISSUE THREAD

**Issue by djcp** [awslabs/awscli-cookbook#13]
This is because awscli depends on `python`, which in turn depends on any version of `build-essential`. The 2.3.0 release of `build-essential` is not chef 11 compatible. The simplest fix I've found is to define build-essential 2.2.4 as a dependency in the Berksfile of my custom cookbook.

**Comment by djcp** [comment]
The python cookbook is "long since deprecated", according to the maintainer.

https://github.com/poise/python/issues/171

This dependency probably needs to be fixed, then.

**Comment by nickryand** [comment]
Looks like the active cookbook is https://supermarket.chef.io/cookbooks/poise-python now. I'll update the dependency and test. I'll be doing the work over at https://github.com/nickryand/awscli-cookbook. 

Thanks for the report!

**Comment by hyandell** [comment]
Closing this issue in favour of Nick's https://github.com/nickryand/cloudcli-cookbook fork.

**Comment by djcp** [comment]
Except that that fork (or is it a separate project) explicitly says that it requires chef 12.
