### ISSUE TITLE
'awscli' as packaged on supermarket is broken

### ISSUE THREAD

**Issue by antiuniverse** [awslabs/awscli-cookbook#2]
Here's a discussion of the underlying issue: https://tickets.opscode.com/browse/CHEF-4107

And log output from OpsWorks illustrating how it manifests:
```
(...)
[2015-01-10T23:02:15+00:00] ERROR: /var/lib/aws/opsworks/cache.stage2/cookbooks/awscli/providers/PaxHeader/s3_file.rb:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
18 gid=1896053708
^
[2015-01-10T23:02:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

If the extended attributes responsible are unintentional or unnecessary, it may be possible to change them and repackage as a workaround. Otherwise, another option would be repackaging and submitting from an unaffected OS version.

**Comment by nickryand** [comment]
Ugh I forgot about this. I'll fix and re-push it later this evening. Thanks for the report!

**Comment by antiuniverse** [comment]
No problem, thanks for the superfast response!

**Comment by nickryand** [comment]
Release 1.0.1 https://supermarket.chef.io/cookbooks/awscli

I'll leave this open until you confirm it looks good. Everything looks good when I downloaded, unpacked and looked through the artifact.

**Comment by antiuniverse** [comment]
Looks good, thanks again!
