### ISSUE TITLE
the new changes are failing for windows

### ISSUE THREAD

**Issue by vickeyrihal1** [awslabs/awscli-cookbook#5]
Hey Nick

Thanks for your work.

Just wanted to highlight one issue with recent changes.

On windows chef client is failing with some "rights: undefined method...... ". The archive is downloading successfully though.

Warm Regards
Vickey Rihal

**Comment by nickryand** [comment]
Can you post the entire error message? I'll try to find a windows machine to test this.

**Comment by vickeyrihal1** [comment]
somehost.somedomain ================================================================================
somehost.somedomain ================================================================================
somehost.somedomain Error executing action `get` on resource 'awscli_s3_file[C:\chef\cache/somebundle-1.1.2.tar.gz]'
somehost.somedomain ================================================================================
somehost.somedomain 
DEBUG: :relay_output_from_backend => ["somehost.somedomain", "NoMethodError\r\n-------------\r\nundefined method `rights' for Chef::Resource::AwscliS3File\r\n\r\nResource Declaration:\r\n---------------------\r\n# In C:/chef/cache/cookbooks/somecookbook-windows/recipes/_somebundle.rb\r\n\r\n  8: awscli_s3_file somebundle_location do\r\n  9:   region \"us-east-1\"\r\n 10:   bucket s3_bucket\r\n 11:   key data_bag_conf['somebundle']\r\n 12:   not_if {File.exists?(\"\#{Chef::Config['file_cache_path']}/\#{data_bag_conf['somebundle']}\")}\r\n 13:   notifies :run, \"powershell_script[remove-item_somebundle]\", :immediately\r\n 14: end\r\n 15: \r\n\r\nCompiled Resource:\r\n------------------\r\n# Declared in C:/chef/cache/cookbooks/somecookbook-windows/recipes/_somebundle.rb:8:in `from_file'\r\n\r\nawscli_s3_file(\"C:\\chef\\cache/somebundle-1.1.2.tar.gz\") do\r\n  action :get\r\n  retries 0\r\n  retry_delay 2\r\n  guard_interpreter :default\r\n  cookbook_name \"somecookbook-windows\"\r\n  recipe_name \"_somebundle\"\r\n  region \"us-east-1\"\r\n  bucket \"somebucket/somepath\"\r\n  key \"somebundle-1.1.2.tar.gz\"\r\n  path \"C:\\\\chef\\\\cache/somebundle-1.1.2.tar.gz\"\r\n  timeout 900\r\n  not_if { #code block }\r\nend\r\n\r\n"]
somehost.somedomain NoMethodError
somehost.somedomain -------------
somehost.somedomain undefined method `rights' for Chef::Resource::AwscliS3File
somehost.somedomain 
somehost.somedomain Resource Declaration:
somehost.somedomain ---------------------
somehost.somedomain # In C:/chef/cache/cookbooks/somecookbook-windows/recipes/_somebundle.rb
somehost.somedomain 
somehost.somedomain   8: awscli_s3_file somebundle_location do
somehost.somedomain   9:   region "us-east-1"
somehost.somedomain  10:   bucket s3_bucket
somehost.somedomain  11:   key data_bag_conf['somebundle']
somehost.somedomain  12:   not_if {File.exists?("#{Chef::Config['file_cache_path']}/#{data_bag_conf['somebundle']}")}
somehost.somedomain  13:   notifies :run, "powershell_script[remove-item_somebundle]", :immediately
somehost.somedomain  14: end
somehost.somedomain  15:

**Comment by nickryand** [comment]
I have uploaded 1.1.2 which should add the guards around the metadata methods not being available.

**Comment by vickeyrihal1** [comment]
Brillian, will give a try.

**Comment by hyandell** [comment]
Closing per nickryand's comment above.
