### ISSUE TITLE
No means to upgrade or set specific version of awscli

### ISSUE THREAD

**Issue by nkadel-skyhook** [awslabs/awscli-cookbook#9]
Since awscli is a developing upstream software package, and thus a moving target, it's important to support upgrading or selecting a specific version of awscli. Do you plan to add something like this? Or would you welcome a patch to add an upgrade option? I've not yet taken on pip based package management through chef, so I'm a bit leery of doing this myself.

**Comment by nickryand** [comment]
A pull request for this is welcome. I have been waiting for someone to need this. I'll get to it if your unable to find the right way. I should have added it the first time around. 

I do not have commit access to this repository any more. I am trying to get that worked out. If you need this really soon, I can add it to my fork and push to supermarket from there.

**Comment by nkadel-skyhook** [comment]
It turns out that the component killing my awscli use was the "certifi" pip installed package, not awscli itself. Rolling back certifi to a previous release solved my issue, at least for today.

I'd still like to see version control, but it would take me much longer to get to it nie.

Nico Kadel-Garcia
Email: nkadel@gmail.com<mailto:kadel@gmail.com>
Sent from iPhone

On Sep 28, 2015, at 23:45, "Nick Downs" <notifications@github.com<mailto:notifications@github.com>> wrote:


A pull request for this is welcome. I have been waiting for someone to need this. I'll get to it if your unable to find the right way. I should have added it the first time around.

I do not have commit access to this repository any more. I am trying to get that worked out. If you need this really soon, I can add it to my fork and push to supermarket from there.

**Comment by hyandell** [comment]
Closing this issue in favour of Nick's https://github.com/nickryand/cloudcli-cookbook fork.
